### ISSUE TITLE
about citation of animations in Polyhedra Viewer

### ISSUE THREAD

**Issue by Rick224339** [tesseralis/polyhedra-viewer#188]
Dear Sir or Madam,

I am a student who recently reads the website Polyhedra Viewer https://polyhedra.tessera.li/.

I am wondering if I want to put some figures of polyhedra into my papers, what should be the right reference and citation format? I usually cite contents from papers but never from a specific website so I have no experience on that.

1. Please provide details about it as far as possible. e.g. in figure, I say "figure is reproduced from Ref. []" or "These structures are created by... []" In bibliography, "author/title/website/HRC/..."

The possible scenaria for use:

One is for my course assignment. (quite simple)

The other is for future possible published papers. (may involve copyright issue)

2. If copying these fantastic figures from this website is not a good idea, could you also recommend some software for me to create polyhedra?

I appreciate it.

Thanks,
Ruikang

**Comment by tesseralis** [comment]
Hi!

Sorry for not seeing this sooner. Your course is probably over, but for future reference of papers, I'm okay with my work being used as long as there is proper attribution (link to the source website and my name). I don't have any preferences for citation style -- that would depend on the publication or standards of your field.

I hope that answers your question.
